export declare enum NotificationType {
    ORDER_CREATED = "ORDER_CREATED",
    PICKUP_ASSIGNED = "PICKUP_ASSIGNED",
    OUT_FOR_PICKUP = "OUT_FOR_PICKUP",
    PICKED_UP = "PICKED_UP",
    RECEIVED_AT_FACILITY = "RECEIVED_AT_FACILITY",
    INSPECTION_STARTED = "INSPECTION_STARTED",
    PRICE_FINALIZED = "PRICE_FINALIZED",
    CUSTOMER_APPROVAL_REQUIRED = "CUSTOMER_APPROVAL_REQUIRED",
    PRICE_APPROVED = "PRICE_APPROVED",
    PRICE_REJECTED = "PRICE_REJECTED",
    PROCESSING_STARTED = "PROCESSING_STARTED",
    QUALITY_CHECK_STARTED = "QUALITY_CHECK_STARTED",
    READY_FOR_DELIVERY = "READY_FOR_DELIVERY",
    DELIVERY_ASSIGNED = "DELIVERY_ASSIGNED",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    DELIVERED = "DELIVERED",
    ORDER_COMPLETED = "ORDER_COMPLETED",
    ORDER_CANCELLED = "ORDER_CANCELLED"
}
//# sourceMappingURL=notificationType.d.ts.map