"use client";

import { useState } from "react";
import Link from "next/link";

import {
  ADMIN_NOTIFICATION_TYPES,
  type AdminNotificationListQuery,
} from "../types/admin-notification.types";

import { useAdminNotifications } from "../hooks/useAdminNotifications";

const getNotificationTypeLabel = (type: string) => {
  return type
    .replaceAll("_", " ")
    .toLowerCase()
    .replace(/\b\w/g, (char) => char.toUpperCase());
};

const getNotificationTypeStyle = (type: string) => {
  switch (type) {
    case "ORDER_CREATED":
      return "bg-blue-100 text-blue-700";

    case "PICKUP_ASSIGNED":
    case "DELIVERY_ASSIGNED":
      return "bg-purple-100 text-purple-700";

    case "OUT_FOR_PICKUP":
    case "OUT_FOR_DELIVERY":
      return "bg-orange-100 text-orange-700";

    case "PICKED_UP":
    case "DELIVERED":
    case "ORDER_COMPLETED":
      return "bg-green-100 text-green-700";

    case "ORDER_CANCELLED":
    case "PRICE_REJECTED":
      return "bg-red-100 text-red-700";

    case "PRICE_FINALIZED":
    case "PRICE_APPROVED":
      return "bg-yellow-100 text-yellow-700";

    default:
      return "bg-gray-100 text-gray-700";
  }
};

const formatDate = (date: string) => {
  return new Date(date).toLocaleString();
};

export default function AdminNotificationsPage() {
  const [page, setPage] = useState(1);

  const [limit] = useState(10);

  const [type, setType] = useState<AdminNotificationListQuery["type"]>();

  const [isRead, setIsRead] = useState<AdminNotificationListQuery["isRead"]>();

  const query: AdminNotificationListQuery = {
    page,
    limit,
    ...(type && { type }),
    ...(typeof isRead === "boolean" && { isRead }),
  };

  const { data, isLoading, isError, error, refetch, isFetching } =
    useAdminNotifications(query);

  const notifications = data?.data.notifications ?? [];

  const pagination = data?.data.pagination;

  const totalPages = pagination?.totalPages ?? 1;

  const handleTypeChange = (value: string) => {
    setPage(1);

    setType(
      value === "" ? undefined : (value as AdminNotificationListQuery["type"]),
    );
  };

  const handleReadStatusChange = (value: string) => {
    setPage(1);

    if (value === "") {
      setIsRead(undefined);
      return;
    }

    setIsRead(value === "read");
  };

  return (
    <div className="space-y-6 p-6">
      {/* Header */}

      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-gray-900">
            Notifications
          </h1>

          <p className="mt-1 text-sm text-gray-500">
            Monitor system notifications generated by the laundry workflow.
          </p>
        </div>

        <button
          type="button"
          onClick={() => refetch()}
          disabled={isFetching}
          className="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-50"
        >
          {isFetching ? "Refreshing..." : "Refresh"}
        </button>
      </div>

      {/* Filters */}

      <div className="rounded-xl border border-gray-200 bg-white p-4 shadow-sm">
        <div className="grid gap-4 md:grid-cols-2">
          {/* Notification Type */}

          <div>
            <label
              htmlFor="notification-type"
              className="mb-2 block text-sm font-medium text-gray-700"
            >
              Notification Type
            </label>

            <select
              id="notification-type"
              value={type ?? ""}
              onChange={(event) => handleTypeChange(event.target.value)}
              className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm text-gray-700 outline-none focus:border-gray-500"
            >
              <option value="">All notification types</option>

              {ADMIN_NOTIFICATION_TYPES.map((notificationType) => (
                <option key={notificationType} value={notificationType}>
                  {getNotificationTypeLabel(notificationType)}
                </option>
              ))}
            </select>
          </div>

          {/* Read Status */}

          <div>
            <label
              htmlFor="notification-status"
              className="mb-2 block text-sm font-medium text-gray-700"
            >
              Read Status
            </label>

            <select
              id="notification-status"
              value={
                typeof isRead !== "boolean" ? "" : isRead ? "read" : "unread"
              }
              onChange={(event) => handleReadStatusChange(event.target.value)}
              className="w-full rounded-lg border border-gray-300 bg-white px-3 py-2.5 text-sm text-gray-700 outline-none focus:border-gray-500"
            >
              <option value="">All notifications</option>

              <option value="unread">Unread</option>

              <option value="read">Read</option>
            </select>
          </div>
        </div>
      </div>

      {/* Loading */}

      {isLoading && (
        <div className="rounded-xl border border-gray-200 bg-white p-10 text-center">
          <p className="text-sm text-gray-500">Loading notifications...</p>
        </div>
      )}

      {/* Error */}

      {isError && !isLoading && (
        <div className="rounded-xl border border-red-200 bg-red-50 p-6">
          <h2 className="font-medium text-red-800">
            Failed to load notifications
          </h2>

          <p className="mt-1 text-sm text-red-600">
            {error instanceof Error
              ? error.message
              : "Something went wrong while loading notifications."}
          </p>

          <button
            type="button"
            onClick={() => refetch()}
            className="mt-4 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700"
          >
            Try Again
          </button>
        </div>
      )}

      {/* Empty */}

      {!isLoading && !isError && notifications.length === 0 && (
        <div className="rounded-xl border border-gray-200 bg-white p-12 text-center">
          <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-gray-100 text-gray-500">
            🔔
          </div>

          <h2 className="mt-4 text-lg font-medium text-gray-900">
            No notifications found
          </h2>

          <p className="mt-1 text-sm text-gray-500">
            There are no notifications matching the selected filters.
          </p>
        </div>
      )}

      {/* Notification List */}

      {!isLoading && !isError && notifications.length > 0 && (
        <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
          <div className="divide-y divide-gray-200">
            {notifications.map((notification) => {
              const userName = notification.userId
                ? `${notification.userId.firstName} ${notification.userId.lastName}`
                : "Unknown user";

              const userEmail =
                notification.userId?.email ?? "No email available";

              return (
                <Link
                  key={notification._id}
                  href={`/admin/notifications/${notification._id}`}
                  className={`block p-5 transition hover:bg-gray-50 ${
                    !notification.isRead ? "bg-blue-50/40" : "bg-white"
                  }`}
                >
                  <div className="flex gap-4">
                    {/* Notification Icon */}

                    <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gray-100 text-lg">
                      🔔
                    </div>

                    {/* Content */}

                    <div className="min-w-0 flex-1">
                      <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                        <div>
                          <div className="flex flex-wrap items-center gap-2">
                            <h2 className="font-medium text-gray-900">
                              {notification.title}
                            </h2>

                            <span
                              className={`rounded-full px-2.5 py-1 text-xs font-medium ${getNotificationTypeStyle(
                                notification.type,
                              )}`}
                            >
                              {getNotificationTypeLabel(notification.type)}
                            </span>

                            {!notification.isRead && (
                              <span className="rounded-full bg-blue-600 px-2.5 py-1 text-xs font-medium text-white">
                                Unread
                              </span>
                            )}
                          </div>

                          <p className="mt-2 text-sm leading-6 text-gray-600">
                            {notification.message}
                          </p>
                        </div>

                        <span className="shrink-0 text-xs text-gray-400">
                          {formatDate(notification.createdAt)}
                        </span>
                      </div>

                      {/* User / Order */}

                      <div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-gray-500">
                        <span>
                          User:{" "}
                          <span className="font-medium text-gray-700">
                            {userName}
                          </span>
                        </span>

                        <span>
                          Email:{" "}
                          <span className="font-medium text-gray-700">
                            {userEmail}
                          </span>
                        </span>

                        {notification.orderId && (
                          <span>
                            Order:{" "}
                            <span className="font-medium text-gray-700">
                              #{notification.orderId._id}
                            </span>
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                </Link>
              );
            })}
          </div>
        </div>
      )}

      {/* Pagination */}

      {!isLoading && !isError && notifications.length > 0 && pagination && (
        <div className="flex flex-col gap-3 rounded-xl border border-gray-200 bg-white p-4 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm text-gray-500">
            Page {pagination.page} of {pagination.totalPages} ·{" "}
            {pagination.total} notifications
          </p>

          <div className="flex items-center gap-2">
            <button
              type="button"
              disabled={pagination.page <= 1}
              onClick={() => setPage((current) => Math.max(1, current - 1))}
              className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-40"
            >
              Previous
            </button>

            <button
              type="button"
              disabled={pagination.page >= pagination.totalPages}
              onClick={() =>
                setPage((current) =>
                  Math.min(pagination.totalPages, current + 1),
                )
              }
              className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-40"
            >
              Next
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
