export declare enum OrderStatus {
    DRAFT = "DRAFT",
    BOOKED = "BOOKED",
    PICKUP_ASSIGNED = "PICKUP_ASSIGNED",
    OUT_FOR_PICKUP = "OUT_FOR_PICKUP",
    PICKED_UP = "PICKED_UP",
    RECEIVED_AT_FACILITY = "RECEIVED_AT_FACILITY",
    INSPECTION_IN_PROGRESS = "INSPECTION_IN_PROGRESS",
    PRICE_FINALIZED = "PRICE_FINALIZED",
    CUSTOMER_APPROVAL_PENDING = "CUSTOMER_APPROVAL_PENDING",
    PROCESSING = "PROCESSING",
    QUALITY_CHECK = "QUALITY_CHECK",
    READY_FOR_DELIVERY = "READY_FOR_DELIVERY",
    DELIVERY_ASSIGNED = "DELIVERY_ASSIGNED",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    DELIVERED = "DELIVERED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    PICKUP_FAILED = "PICKUP_FAILED",
    DELIVERY_FAILED = "DELIVERY_FAILED",
    ON_HOLD = "ON_HOLD"
}
//# sourceMappingURL=orderStatus.d.ts.map